// Objective-C API for talking to dsa/eth Go package.
//   gobind -lang=objc dsa/eth
//
// File is generated by gobind. Do not edit.

#ifndef __Dsa_H__
#define __Dsa_H__

@import Foundation;
#include "Universe.objc.h"


FOUNDATION_EXPORT NSString* DsaSig(NSString* pri, NSString* sha);

#endif
