
// Objective-C API for talking to the following Go packages
//
//	sha/eth
//	dsa/eth
//	ies/eth
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Ean_FRAMEWORK_H__
#define __Ean_FRAMEWORK_H__

#include "Ean.objc.h"
#include "Dsa.objc.h"
#include "Ies.objc.h"
#include "universe.objc.h"

#endif
