// Objective-C API for talking to sha/eth Go package.
//   gobind -lang=objc sha/eth
//
// File is generated by gobind. Do not edit.

#ifndef __Ean_H__
#define __Ean_H__

@import Foundation;
#include "Universe.objc.h"


FOUNDATION_EXPORT NSString* EanSha(NSData* msg);

#endif
