// Objective-C API for talking to ies/eth Go package.
//   gobind -lang=objc ies/eth
//
// File is generated by gobind. Do not edit.

#ifndef __Ies_H__
#define __Ies_H__

@import Foundation;
#include "Universe.objc.h"


FOUNDATION_EXPORT NSString* IesEnc(NSString* pub, NSData* tkn, NSData* msg);

#endif
